## For more information about this file, see: 
## https://github.com/sestaton/Transposome/wiki/Specifications-and-example-usage.
blast_input:
  - sequence_file:      t_reads.fas
  - sequence_format:    fasta
  - thread:             2
  - output_directory:   transposome_results_out
clustering_options:
  - in_memory:          1
  - percent_identity:   90
  - fraction_coverage:  0.55
  - merge_threshold:    100
annotation_input:
  - repeat_database:    repeats.fas
annotation_options:
  - cluster_size:       100
output:
  - run_log_file:       t_log.txt
  - cluster_log_file:   t_cluster_report.txt
